# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0005_auto_20171025_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='simple_name',
            field=models.TextField(blank=True),
        ),
    ]
